/* The following code was generated by JFlex 1.4.3 on 8/11/14 01:18 AM */

package tools;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/11/14 01:18 AM from the specification file
 * <tt>src/tools/ALexico.flex</tt>
 */
class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\16\1\0\1\1\1\17\22\0\1\2\1\50\1\23"+
    "\2\0\1\44\2\0\1\52\1\53\1\21\1\42\1\54\1\43\1\6"+
    "\1\20\2\5\10\3\1\0\1\51\1\47\1\45\1\46\2\0\1\13"+
    "\2\13\1\13\1\22\6\13\1\13\1\13\1\13\1\13\2\13\1\13"+
    "\2\13\1\13\2\13\1\22\2\13\1\55\1\0\1\56\3\0\1\10"+
    "\1\33\1\25\1\12\1\30\1\37\1\7\1\40\1\32\2\7\1\26"+
    "\1\35\1\11\1\14\1\31\1\7\1\15\1\27\1\34\1\41\1\36"+
    "\1\7\1\4\2\7\1\0\1\24\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\6\4\1\6"+
    "\1\7\1\1\1\10\13\4\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\1\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\0\1\3\1\0\3\4\1\25\1\26\1\4"+
    "\1\2\4\0\1\27\3\4\1\30\13\4\1\31\1\32"+
    "\1\33\1\34\2\0\1\35\4\4\1\25\1\4\2\2"+
    "\2\0\1\27\17\4\1\36\2\0\1\37\4\4\2\0"+
    "\1\2\2\4\1\40\1\41\14\4\1\3\1\4\1\42"+
    "\2\4\1\0\1\4\1\43\12\4\1\44\1\45\3\4"+
    "\1\46\2\4\1\47\7\4\1\50\7\4\1\51\1\52"+
    "\2\4\1\53\1\54\1\55\1\56\1\57\2\4\1\60"+
    "\3\4\1\61\2\4\1\62\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\274\0\57\0\353"+
    "\0\u011a\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\57\0\u0234"+
    "\0\57\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d"+
    "\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\57\0\u04c6"+
    "\0\57\0\57\0\u04f5\0\57\0\57\0\57\0\57\0\57"+
    "\0\57\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e"+
    "\0\274\0\u066d\0\u069c\0\u06cb\0\u0234\0\u06fa\0\u0729\0\u0234"+
    "\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1"+
    "\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\57"+
    "\0\57\0\57\0\57\0\u0a19\0\u0a48\0\274\0\u0a77\0\u0aa6"+
    "\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96"+
    "\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e"+
    "\0\57\0\u0553\0\u0f3d\0\274\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9"+
    "\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4\0\274\0\274\0\u1113"+
    "\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b"+
    "\0\u12ba\0\u12e9\0\u1318\0\u0f3d\0\u1347\0\274\0\u1376\0\u13a5"+
    "\0\u13d4\0\u1403\0\274\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee"+
    "\0\u151d\0\u154c\0\u157b\0\u15aa\0\u15d9\0\274\0\274\0\u1608"+
    "\0\u1637\0\u1666\0\274\0\u1695\0\u16c4\0\274\0\u16f3\0\u1722"+
    "\0\u1751\0\u1780\0\u17af\0\u17de\0\u180d\0\274\0\u183c\0\u186b"+
    "\0\u189a\0\u18c9\0\u18f8\0\u1927\0\u1956\0\274\0\274\0\u1985"+
    "\0\u19b4\0\274\0\274\0\274\0\274\0\274\0\u19e3\0\u1a12"+
    "\0\274\0\u1a41\0\u1a70\0\u1a9f\0\274\0\u1ace\0\u1afd\0\274"+
    "\0\274";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\6"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\2\3\1\16"+
    "\1\17\1\13\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\6\1\31\1\32\1\33\1\34"+
    "\1\6\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\61\0\1\52"+
    "\57\0\1\53\1\0\1\53\1\54\53\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\2\6\1\55\4\6\4\0\1\6\2\0\15\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\14\6\1\56"+
    "\20\0\3\6\1\0\7\6\4\0\1\6\2\0\3\6"+
    "\1\57\11\6\20\0\1\6\1\60\1\6\1\0\7\60"+
    "\4\0\1\60\2\0\15\60\20\0\3\6\1\0\6\6"+
    "\1\61\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\3\6\1\62\11\6\35\0"+
    "\1\63\1\64\35\0\16\65\1\66\1\67\3\65\1\70"+
    "\33\65\3\0\3\6\1\0\1\6\1\71\5\6\4\0"+
    "\1\6\2\0\1\6\1\72\13\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\3\6\1\73\11\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\5\6\1\74"+
    "\7\6\20\0\1\6\1\75\1\6\1\0\2\6\1\76"+
    "\4\6\4\0\1\6\2\0\2\6\1\77\12\6\20\0"+
    "\3\6\1\0\6\6\1\100\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\2\6\1\101\4\6\4\0\1\6"+
    "\2\0\15\6\20\0\3\6\1\0\5\6\1\102\1\6"+
    "\4\0\1\6\2\0\15\6\20\0\3\6\1\0\7\6"+
    "\4\0\1\6\2\0\3\6\1\103\1\6\1\104\7\6"+
    "\20\0\3\6\1\0\7\6\4\0\1\6\2\0\3\6"+
    "\1\105\11\6\20\0\3\6\1\0\1\6\1\106\5\6"+
    "\4\0\1\6\2\0\15\6\20\0\3\6\1\0\1\6"+
    "\1\107\5\6\4\0\1\6\2\0\15\6\57\0\1\110"+
    "\57\0\1\111\60\0\1\112\56\0\1\113\13\0\1\114"+
    "\57\0\1\53\1\0\1\53\54\0\1\115\1\0\1\115"+
    "\54\0\3\6\1\0\3\6\1\116\3\6\4\0\1\6"+
    "\2\0\15\6\20\0\3\6\1\0\7\6\4\0\1\6"+
    "\2\0\1\6\1\117\13\6\20\0\3\6\1\0\7\6"+
    "\4\0\1\6\2\0\1\120\1\6\1\121\6\6\1\122"+
    "\3\6\20\0\1\123\1\60\1\123\1\0\7\60\4\0"+
    "\1\60\2\0\15\60\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\7\6\1\124\5\6\15\0\16\63\1\125"+
    "\1\126\37\63\21\127\1\130\35\127\23\0\1\131\51\0"+
    "\1\66\4\0\1\131\36\0\3\6\1\0\3\6\1\132"+
    "\3\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\1\6\1\133\5\6\4\0\1\6\2\0\15\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\3\6\1\134"+
    "\11\6\20\0\3\6\1\0\2\6\1\135\4\6\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\7\6\1\136\5\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\7\6\1\137\5\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\1\140\14\6"+
    "\20\0\3\6\1\0\5\6\1\141\1\6\4\0\1\6"+
    "\2\0\15\6\20\0\3\6\1\0\7\6\4\0\1\6"+
    "\2\0\1\142\14\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\1\6\1\143\13\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\7\6\1\144\5\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\3\6\1\145"+
    "\11\6\20\0\3\6\1\0\6\6\1\146\4\0\1\6"+
    "\2\0\15\6\20\0\3\6\1\0\7\6\4\0\1\6"+
    "\2\0\1\6\1\147\13\6\20\0\3\6\1\0\7\6"+
    "\4\0\1\6\2\0\1\150\14\6\17\0\1\151\57\0"+
    "\1\115\1\152\1\153\14\0\1\152\5\0\1\152\31\0"+
    "\3\6\1\0\5\6\1\154\1\6\4\0\1\6\2\0"+
    "\15\6\20\0\3\6\1\0\7\6\4\0\1\6\2\0"+
    "\5\6\1\155\7\6\20\0\3\6\1\0\3\6\1\156"+
    "\3\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\5\6\1\157\1\6\4\0\1\6\2\0\15\6\20\0"+
    "\1\123\1\6\1\123\1\0\7\6\4\0\1\6\2\0"+
    "\15\6\20\0\3\6\1\0\5\6\1\160\1\6\4\0"+
    "\1\6\2\0\15\6\35\0\1\161\54\0\1\125\1\0"+
    "\1\161\36\0\21\127\1\162\35\127\20\0\1\163\1\130"+
    "\60\0\1\65\36\0\3\6\1\0\7\6\4\0\1\6"+
    "\2\0\3\6\1\164\11\6\20\0\3\6\1\0\7\6"+
    "\4\0\1\6\2\0\2\6\1\165\12\6\20\0\3\6"+
    "\1\0\6\6\1\166\4\0\1\6\2\0\15\6\20\0"+
    "\3\6\1\0\5\6\1\167\1\6\4\0\1\6\2\0"+
    "\15\6\20\0\3\6\1\0\7\6\4\0\1\6\2\0"+
    "\5\6\1\170\7\6\20\0\3\6\1\0\5\6\1\171"+
    "\1\6\4\0\1\6\2\0\3\6\1\172\11\6\20\0"+
    "\3\6\1\0\6\6\1\173\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\7\6\4\0\1\6\2\0\4\6"+
    "\1\174\10\6\20\0\3\6\1\0\6\6\1\175\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\3\6\1\176\11\6\20\0\3\6\1\0"+
    "\5\6\1\177\1\6\4\0\1\6\2\0\15\6\20\0"+
    "\3\6\1\0\2\6\1\200\4\6\4\0\1\6\2\0"+
    "\15\6\20\0\3\6\1\0\3\6\1\201\3\6\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\2\6\1\202\12\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\3\6\1\203\11\6\20\0"+
    "\1\204\1\152\1\204\14\0\1\152\5\0\1\152\31\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\10\6\1\205"+
    "\4\6\20\0\3\6\1\0\7\6\4\0\1\6\2\0"+
    "\3\6\1\206\11\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\1\6\1\207\13\6\20\0\3\6\1\0"+
    "\6\6\1\210\4\0\1\6\2\0\15\6\35\0\1\63"+
    "\36\0\20\127\1\163\1\162\35\127\20\0\1\211\41\0"+
    "\3\6\1\0\2\6\1\212\4\6\4\0\1\6\2\0"+
    "\15\6\20\0\3\6\1\0\7\6\4\0\1\6\2\0"+
    "\3\6\1\213\11\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\3\6\1\214\11\6\20\0\3\6\1\0"+
    "\2\6\1\215\4\6\4\0\1\6\2\0\15\6\20\0"+
    "\3\6\1\0\6\6\1\216\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\7\6\4\0\1\6\2\0\5\6"+
    "\1\217\7\6\20\0\3\6\1\0\7\6\4\0\1\6"+
    "\2\0\5\6\1\220\7\6\20\0\3\6\1\0\7\6"+
    "\4\0\1\6\2\0\3\6\1\221\11\6\20\0\3\6"+
    "\1\0\1\6\1\222\5\6\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\3\6\1\223\3\6\4\0\1\6"+
    "\2\0\15\6\20\0\3\6\1\0\7\6\4\0\1\6"+
    "\2\0\7\6\1\224\5\6\20\0\3\6\1\0\1\6"+
    "\1\225\5\6\4\0\1\6\2\0\15\6\20\0\3\6"+
    "\1\0\5\6\1\226\1\6\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\6\6\1\227\4\0\1\6\2\0"+
    "\15\6\20\0\3\6\1\0\1\6\1\230\5\6\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\11\6\1\231\3\6\20\0\3\6\1\0"+
    "\2\6\1\232\4\6\4\0\1\6\2\0\15\6\36\0"+
    "\1\64\40\0\3\6\1\0\1\6\1\233\5\6\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\2\6\1\234"+
    "\4\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\1\235\14\6\20\0\3\6"+
    "\1\0\5\6\1\236\1\6\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\7\6\4\0\1\6\2\0\6\6"+
    "\1\237\6\6\20\0\3\6\1\0\7\6\4\0\1\6"+
    "\2\0\3\6\1\240\11\6\20\0\3\6\1\0\7\6"+
    "\4\0\1\6\2\0\10\6\1\241\4\6\20\0\3\6"+
    "\1\0\2\6\1\242\4\6\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\5\6\1\243\1\6\4\0\1\6"+
    "\2\0\15\6\20\0\3\6\1\0\6\6\1\244\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\3\6\1\245"+
    "\3\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\1\6\1\246\13\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\3\6\1\247"+
    "\11\6\20\0\3\6\1\0\1\6\1\250\5\6\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\3\6\1\251"+
    "\3\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\3\6\1\252\11\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\5\6\1\253"+
    "\7\6\20\0\3\6\1\0\3\6\1\254\3\6\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\3\6\1\255\11\6\20\0\3\6\1\0"+
    "\5\6\1\256\1\6\4\0\1\6\2\0\15\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\2\6\1\257"+
    "\12\6\20\0\3\6\1\0\1\6\1\260\5\6\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\7\6\4\0"+
    "\1\6\2\0\3\6\1\261\11\6\20\0\3\6\1\0"+
    "\6\6\1\262\4\0\1\6\2\0\15\6\20\0\3\6"+
    "\1\0\6\6\1\263\4\0\1\6\2\0\15\6\20\0"+
    "\3\6\1\0\7\6\4\0\1\6\2\0\3\6\1\264"+
    "\11\6\20\0\3\6\1\0\7\6\4\0\1\6\2\0"+
    "\2\6\1\265\12\6\20\0\3\6\1\0\6\6\1\266"+
    "\4\0\1\6\2\0\15\6\20\0\3\6\1\0\1\6"+
    "\1\267\5\6\4\0\1\6\2\0\15\6\20\0\3\6"+
    "\1\0\2\6\1\270\4\6\4\0\1\6\2\0\15\6"+
    "\20\0\3\6\1\0\7\6\4\0\1\6\2\0\2\6"+
    "\1\271\12\6\20\0\3\6\1\0\6\6\1\272\4\0"+
    "\1\6\2\0\15\6\20\0\3\6\1\0\3\6\1\273"+
    "\3\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\7\6\1\274\5\6\20\0"+
    "\3\6\1\0\5\6\1\275\1\6\4\0\1\6\2\0"+
    "\15\6\20\0\3\6\1\0\7\6\4\0\1\6\2\0"+
    "\3\6\1\276\11\6\20\0\3\6\1\0\1\6\1\277"+
    "\5\6\4\0\1\6\2\0\15\6\20\0\3\6\1\0"+
    "\7\6\4\0\1\6\2\0\2\6\1\300\12\6\20\0"+
    "\3\6\1\0\6\6\1\301\4\0\1\6\2\0\15\6"+
    "\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6956];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\7\1\1\11\1\1\1\11"+
    "\15\1\1\11\1\1\2\11\1\1\6\11\1\0\1\1"+
    "\1\0\7\1\4\0\20\1\4\11\2\0\11\1\2\0"+
    "\20\1\1\11\2\0\5\1\2\0\26\1\1\0\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[193];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return new Symbol(sym.CC, new token(yyline,"ESPECIALES", yytext()));
          }
        case 52: break;
        case 51: 
          { return new Symbol(sym.INCREMENTAR, new token(yyline,"RESERVADA", yytext()));
          }
        case 53: break;
        case 38: 
          { return new Symbol(sym.CADENA, new token(yyline,"RESERVADA", yytext()));
          }
        case 54: break;
        case 37: 
          { return new Symbol(sym.HACER, new token(yyline,"RESERVADA", yytext()));
          }
        case 55: break;
        case 31: 
          { return new Symbol(sym.NULO, new token(yyline,"RESERVADA", yytext()));
          }
        case 56: break;
        case 26: 
          { return new Symbol(sym.MMENOS, new token(yyline,"OPERADOR", yytext()));
          }
        case 57: break;
        case 17: 
          { return new Symbol(sym.PC, new token(yyline,"ESPECIALES", yytext()));
          }
        case 58: break;
        case 24: 
          { return new Symbol(sym.SI, new token(yyline,"RESERVADA", yytext()));
          }
        case 59: break;
        case 46: 
          { return new Symbol(sym.ENTONCES, new token(yyline,"RESERVADA", yytext()));
          }
        case 60: break;
        case 48: 
          { return new Symbol(sym.MIENTRAS, new token(yyline,"RESERVADA", yytext()));
          }
        case 61: break;
        case 32: 
          { return new Symbol(sym.LEER, new token(yyline,"RESERVADA", yytext()));
          }
        case 62: break;
        case 6: 
          { return new Symbol(sym.DIAGONAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 63: break;
        case 36: 
          { return new Symbol(sym.FALSO, new token(yyline,"RESERVADA", yytext()));
          }
        case 64: break;
        case 4: 
          { return new Symbol(sym.VARIABLE, new token(yyline,"ID",yytext()));
          }
        case 65: break;
        case 34: 
          { return new Symbol(sym.DESDE, new token(yyline,"RESERVADA", yytext()));
          }
        case 66: break;
        case 19: 
          { return new Symbol(sym.CA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 67: break;
        case 30: 
          { return new Symbol(sym.TAB, new token(yyline, "TAB", yytext(), true));
          }
        case 68: break;
        case 41: 
          { return new Symbol(sym.BOLEANO, new token(yyline,"RESERVADA", yytext()));
          }
        case 69: break;
        case 43: 
          { return new Symbol(sym.DEVOLVER, new token(yyline,"RESERVADA", yytext()));
          }
        case 70: break;
        case 40: 
          { return new Symbol(sym.DECIMAL, new token(yyline,"RESERVADA", yytext()));
          }
        case 71: break;
        case 2: 
          { /*ignore*/
          }
        case 72: break;
        case 33: 
          { return new Symbol(sym.SINO, new token(yyline,"RESERVADA", yytext()));
          }
        case 73: break;
        case 16: 
          { return new Symbol(sym.PA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 74: break;
        case 5: 
          { return new Symbol(sym.PUNTO, new token(yyline,"ESPECIALES", yytext()));
          }
        case 75: break;
        case 11: 
          { return new Symbol(sym.MODULO, new token(yyline,"OPERADOR", yytext()));
          }
        case 76: break;
        case 49: 
          { return new Symbol(sym.VERDADERO, new token(yyline,"RESERVADA", yytext()));
          }
        case 77: break;
        case 39: 
          { return new Symbol(sym.ENTERO, new token(yyline,"RESERVADA", yytext()));
          }
        case 78: break;
        case 12: 
          { return new Symbol(sym.IGUAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 79: break;
        case 7: 
          { return new Symbol(sym.MULTIPLICACION, new token(yyline,"OPERADOR", yytext()));
          }
        case 80: break;
        case 13: 
          { return new Symbol(sym.MAYORQUE, new token(yyline,"OPERADOR", yytext()));
          }
        case 81: break;
        case 28: 
          { return new Symbol(sym.DIFERENCIA, new token(yyline,"OPERADOR", yytext()));
          }
        case 82: break;
        case 23: 
          { return new Symbol(sym.CADENAS, new token(yyline,"CADENAS", yytext()));
          }
        case 83: break;
        case 14: 
          { return new Symbol(sym.MENORQUE, new token(yyline,"OPERADOR", yytext()));
          }
        case 84: break;
        case 10: 
          { return new Symbol(sym.RESTA, new token(yyline,"OPERADOR", yytext()));
          }
        case 85: break;
        case 21: 
          { return new Symbol(sym.NOMCLASE, new token(yyline,"ID", yytext()));
          }
        case 86: break;
        case 9: 
          { return new Symbol(sym.SUMA, new token(yyline,"OPERADOR", yytext()));
          }
        case 87: break;
        case 47: 
          { return new Symbol(sym.ESCRIBIR, new token(yyline,"RESERVADA", yytext()));
          }
        case 88: break;
        case 29: 
          { return new Symbol(sym.AND, new token(yyline,"RESERVADA", yytext()));
          }
        case 89: break;
        case 1: 
          { yyclose(); 
    System.err.println("Caracter Invalido" + yytext() + "["+ yyline + "]");
    return new Symbol(sym.ERROR);
          }
        case 90: break;
        case 44: 
          { return new Symbol(sym.RETORNAR, new token(yyline,"RESERVADA", yytext()));
          }
        case 91: break;
        case 15: 
          { return new Symbol(sym.PCOMA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 92: break;
        case 50: 
          { return new Symbol(sym.PROPIEDADES, new token(yyline,"RESERVADA", yytext()));
          }
        case 93: break;
        case 45: 
          { return new Symbol(sym.EXTIENDE, new token(yyline,"RESERVADA", yytext()));
          }
        case 94: break;
        case 22: 
          { return new Symbol(sym.OR, new token(yyline,"RESERVADA", yytext()));
          }
        case 95: break;
        case 35: 
          { return new Symbol(sym.CLASE, new token(yyline,"RESERVADA", yytext()));
          }
        case 96: break;
        case 25: 
          { return new Symbol(sym.MMAS, new token(yyline,"OPERADOR", yytext()));
          }
        case 97: break;
        case 3: 
          { return new Symbol(sym.NUMERO, new token(yyline,"NUMERO", yytext()));
          }
        case 98: break;
        case 8: 
          { return new Symbol(sym.OPCION, new token(yyline,"OPERADOR", yytext()));
          }
        case 99: break;
        case 18: 
          { return new Symbol(sym.COMA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 100: break;
        case 42: 
          { return new Symbol(sym.METODOS, new token(yyline,"RESERVADA", yytext()));
          }
        case 101: break;
        case 27: 
          { return new Symbol(sym.IIGUAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 102: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   System.out.println("Fin de archivo encontrado");
  return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
