/* The following code was generated by JFlex 1.4.3 on 16/11/14 08:24 PM */

package tools;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16/11/14 08:24 PM from the specification file
 * <tt>src/tools/ALexico.flex</tt>
 */
class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\15\1\0\1\23\1\16\22\0\1\2\1\47\1\21"+
    "\2\0\1\43\2\0\1\51\1\52\1\20\1\41\1\53\1\42\1\5"+
    "\1\17\2\3\10\3\1\0\1\50\1\46\1\44\1\45\2\0\1\12"+
    "\2\12\1\12\1\12\6\12\1\12\1\12\1\12\1\12\2\12\1\12"+
    "\2\12\1\12\2\12\1\12\2\12\1\54\1\0\1\55\3\0\1\7"+
    "\1\32\1\24\1\11\1\27\1\36\1\6\1\37\1\31\2\6\1\25"+
    "\1\34\1\10\1\13\1\30\1\6\1\14\1\26\1\33\1\40\1\35"+
    "\1\6\1\4\2\6\1\0\1\22\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\6\5"+
    "\1\7\1\10\1\11\1\1\1\12\1\3\13\5\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\1\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\0\1\4\1\0\4\5"+
    "\1\27\1\30\1\5\1\3\4\0\1\31\3\5\1\32"+
    "\13\5\1\33\1\34\1\35\1\36\1\0\1\37\1\40"+
    "\4\5\1\27\1\5\2\3\2\0\1\31\17\5\1\41"+
    "\4\5\2\0\1\3\2\5\1\42\1\43\15\5\1\44"+
    "\2\5\1\0\1\5\1\45\12\5\1\46\1\47\3\5"+
    "\1\50\2\5\1\51\7\5\1\52\7\5\1\53\1\54"+
    "\2\5\1\55\1\56\1\57\1\60\1\61\2\5\1\62"+
    "\3\5\1\63\2\5\1\64\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\56\0\134\0\212\0\270\0\56\0\346"+
    "\0\u0114\0\u0142\0\u0170\0\u019e\0\u01cc\0\56\0\u01fa\0\56"+
    "\0\u0228\0\56\0\56\0\u0256\0\u0284\0\u02b2\0\u02e0\0\u030e"+
    "\0\u033c\0\u036a\0\u0398\0\u03c6\0\u03f4\0\u0422\0\u0450\0\u047e"+
    "\0\56\0\u04ac\0\56\0\56\0\u04da\0\56\0\56\0\56"+
    "\0\56\0\56\0\56\0\u0508\0\u0536\0\u0564\0\u0592\0\u05c0"+
    "\0\u05ee\0\u061c\0\u064a\0\270\0\u0678\0\u06a6\0\u06d4\0\u0228"+
    "\0\u0702\0\u0730\0\u0228\0\u075e\0\u078c\0\u07ba\0\u07e8\0\u0816"+
    "\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986"+
    "\0\u09b4\0\u09e2\0\56\0\56\0\56\0\56\0\u0a10\0\u0564"+
    "\0\270\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52"+
    "\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66\0\u0c94\0\u0cc2"+
    "\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04\0\u0e32"+
    "\0\u0e60\0\u0e8e\0\u0ebc\0\270\0\u0eea\0\u0f18\0\u0f46\0\u0f74"+
    "\0\u0fa2\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\270\0\270\0\u1088"+
    "\0\u10b6\0\u10e4\0\u1112\0\u1140\0\u116e\0\u119c\0\u11ca\0\u11f8"+
    "\0\u1226\0\u1254\0\u1282\0\u12b0\0\270\0\u12de\0\u130c\0\u133a"+
    "\0\u1368\0\270\0\u1396\0\u13c4\0\u13f2\0\u1420\0\u144e\0\u147c"+
    "\0\u14aa\0\u14d8\0\u1506\0\u1534\0\270\0\270\0\u1562\0\u1590"+
    "\0\u15be\0\270\0\u15ec\0\u161a\0\270\0\u1648\0\u1676\0\u16a4"+
    "\0\u16d2\0\u1700\0\u172e\0\u175c\0\270\0\u178a\0\u17b8\0\u17e6"+
    "\0\u1814\0\u1842\0\u1870\0\u189e\0\270\0\270\0\u18cc\0\u18fa"+
    "\0\270\0\270\0\270\0\270\0\270\0\u1928\0\u1956\0\270"+
    "\0\u1984\0\u19b2\0\u19e0\0\270\0\u1a0e\0\u1a3c\0\270\0\270";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\6\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\2\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\6\1\33\1\34\1\35\1\36\1\6"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\60\0\1\54\56\0"+
    "\1\55\1\0\1\56\53\0\1\57\1\6\1\0\7\6"+
    "\7\0\15\6\20\0\1\57\1\6\1\0\2\6\1\60"+
    "\4\6\7\0\15\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\14\6\1\61\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\3\6\1\62\11\6\20\0\1\57\1\63\1\0"+
    "\7\63\7\0\15\63\20\0\1\57\1\6\1\0\6\6"+
    "\1\64\7\0\15\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\3\6\1\65\11\6\34\0\1\66\1\67\35\0"+
    "\15\70\1\71\1\72\2\70\1\73\34\70\3\0\1\57"+
    "\1\6\1\0\1\6\1\74\5\6\7\0\1\6\1\75"+
    "\13\6\20\0\1\57\1\6\1\0\7\6\7\0\3\6"+
    "\1\76\11\6\20\0\1\57\1\6\1\0\7\6\7\0"+
    "\5\6\1\77\7\6\20\0\1\57\1\100\1\0\2\6"+
    "\1\101\4\6\7\0\2\6\1\102\12\6\20\0\1\57"+
    "\1\6\1\0\6\6\1\103\7\0\15\6\20\0\1\57"+
    "\1\6\1\0\2\6\1\104\4\6\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\5\6\1\105\1\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\3\6\1\106"+
    "\1\6\1\107\7\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\3\6\1\110\11\6\20\0\1\57\1\6\1\0"+
    "\1\6\1\111\5\6\7\0\15\6\20\0\1\57\1\6"+
    "\1\0\1\6\1\112\5\6\7\0\15\6\56\0\1\113"+
    "\56\0\1\114\57\0\1\115\55\0\1\116\13\0\1\117"+
    "\56\0\1\55\55\0\1\120\55\0\1\57\55\0\1\57"+
    "\1\6\1\0\3\6\1\121\3\6\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\7\6\7\0\1\6\1\122\13\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\1\123\1\6"+
    "\1\124\6\6\1\125\3\6\20\0\1\126\1\63\1\0"+
    "\7\63\7\0\15\63\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\7\6\1\127\5\6\15\0\15\66\1\130\1\131"+
    "\37\66\20\132\1\133\35\132\21\0\1\134\51\0\1\71"+
    "\3\0\1\134\37\0\1\57\1\6\1\0\3\6\1\135"+
    "\3\6\7\0\15\6\20\0\1\57\1\6\1\0\1\6"+
    "\1\136\5\6\7\0\15\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\3\6\1\137\11\6\20\0\1\57\1\6"+
    "\1\0\2\6\1\140\4\6\7\0\15\6\20\0\1\57"+
    "\1\6\1\0\7\6\7\0\7\6\1\141\5\6\20\0"+
    "\1\57\1\6\1\0\7\6\7\0\7\6\1\142\5\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\1\143\14\6"+
    "\20\0\1\57\1\6\1\0\5\6\1\144\1\6\7\0"+
    "\15\6\20\0\1\57\1\6\1\0\7\6\7\0\1\145"+
    "\14\6\20\0\1\57\1\6\1\0\7\6\7\0\1\6"+
    "\1\146\13\6\20\0\1\57\1\6\1\0\7\6\7\0"+
    "\7\6\1\147\5\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\3\6\1\150\11\6\20\0\1\57\1\6\1\0"+
    "\6\6\1\151\7\0\15\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\1\6\1\152\13\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\1\153\14\6\17\0\1\3\56\0"+
    "\1\57\1\6\1\0\5\6\1\154\1\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\5\6\1\155"+
    "\7\6\20\0\1\57\1\6\1\0\3\6\1\156\3\6"+
    "\7\0\15\6\20\0\1\57\1\6\1\0\5\6\1\157"+
    "\1\6\7\0\15\6\20\0\1\126\55\0\1\57\1\6"+
    "\1\0\5\6\1\160\1\6\7\0\15\6\34\0\1\161"+
    "\53\0\1\130\1\0\1\161\36\0\20\132\1\162\35\132"+
    "\17\0\1\163\1\133\56\0\1\70\37\0\1\57\1\6"+
    "\1\0\7\6\7\0\3\6\1\164\11\6\20\0\1\57"+
    "\1\6\1\0\7\6\7\0\2\6\1\165\12\6\20\0"+
    "\1\57\1\6\1\0\6\6\1\166\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\5\6\1\167\1\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\5\6\1\170"+
    "\7\6\20\0\1\57\1\6\1\0\5\6\1\171\1\6"+
    "\7\0\3\6\1\172\11\6\20\0\1\57\1\6\1\0"+
    "\6\6\1\173\7\0\15\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\4\6\1\174\10\6\20\0\1\57\1\6"+
    "\1\0\6\6\1\175\7\0\15\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\3\6\1\176\11\6\20\0\1\57"+
    "\1\6\1\0\5\6\1\177\1\6\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\2\6\1\200\4\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\3\6\1\201\3\6\7\0"+
    "\15\6\20\0\1\57\1\6\1\0\7\6\7\0\2\6"+
    "\1\202\12\6\20\0\1\57\1\6\1\0\7\6\7\0"+
    "\3\6\1\203\11\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\10\6\1\204\4\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\3\6\1\205\11\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\1\6\1\206\13\6\20\0\1\57"+
    "\1\6\1\0\6\6\1\207\7\0\15\6\34\0\1\66"+
    "\36\0\17\132\1\163\1\162\35\132\17\0\1\210\41\0"+
    "\1\57\1\6\1\0\2\6\1\211\4\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\3\6\1\212"+
    "\11\6\20\0\1\57\1\6\1\0\7\6\7\0\3\6"+
    "\1\213\11\6\20\0\1\57\1\6\1\0\2\6\1\214"+
    "\4\6\7\0\15\6\20\0\1\57\1\6\1\0\6\6"+
    "\1\215\7\0\15\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\5\6\1\216\7\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\5\6\1\217\7\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\3\6\1\220\11\6\20\0\1\57"+
    "\1\6\1\0\1\6\1\221\5\6\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\3\6\1\222\3\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\7\6\1\223"+
    "\5\6\20\0\1\57\1\6\1\0\1\6\1\224\5\6"+
    "\7\0\15\6\20\0\1\57\1\6\1\0\5\6\1\225"+
    "\1\6\7\0\15\6\20\0\1\57\1\6\1\0\6\6"+
    "\1\226\7\0\15\6\20\0\1\57\1\6\1\0\1\6"+
    "\1\227\5\6\7\0\15\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\11\6\1\230\3\6\20\0\1\57\1\6"+
    "\1\0\2\6\1\231\4\6\7\0\15\6\35\0\1\67"+
    "\40\0\1\57\1\6\1\0\1\6\1\232\5\6\7\0"+
    "\15\6\20\0\1\57\1\6\1\0\2\6\1\233\4\6"+
    "\7\0\15\6\20\0\1\57\1\6\1\0\7\6\7\0"+
    "\1\234\14\6\20\0\1\57\1\6\1\0\5\6\1\235"+
    "\1\6\7\0\15\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\6\6\1\236\6\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\3\6\1\237\11\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\10\6\1\240\4\6\20\0\1\57"+
    "\1\6\1\0\2\6\1\241\4\6\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\5\6\1\242\1\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\6\6\1\243\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\3\6\1\244\3\6\7\0"+
    "\15\6\20\0\1\57\1\6\1\0\7\6\7\0\1\6"+
    "\1\245\13\6\20\0\1\57\1\6\1\0\7\6\7\0"+
    "\3\6\1\246\11\6\20\0\1\57\1\6\1\0\1\6"+
    "\1\247\5\6\7\0\15\6\20\0\1\57\1\6\1\0"+
    "\3\6\1\250\3\6\7\0\15\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\3\6\1\251\11\6\20\0\1\57"+
    "\1\6\1\0\7\6\7\0\5\6\1\252\7\6\20\0"+
    "\1\57\1\6\1\0\3\6\1\253\3\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\7\6\7\0\3\6\1\254"+
    "\11\6\20\0\1\57\1\6\1\0\5\6\1\255\1\6"+
    "\7\0\15\6\20\0\1\57\1\6\1\0\7\6\7\0"+
    "\2\6\1\256\12\6\20\0\1\57\1\6\1\0\1\6"+
    "\1\257\5\6\7\0\15\6\20\0\1\57\1\6\1\0"+
    "\7\6\7\0\3\6\1\260\11\6\20\0\1\57\1\6"+
    "\1\0\6\6\1\261\7\0\15\6\20\0\1\57\1\6"+
    "\1\0\6\6\1\262\7\0\15\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\3\6\1\263\11\6\20\0\1\57"+
    "\1\6\1\0\7\6\7\0\2\6\1\264\12\6\20\0"+
    "\1\57\1\6\1\0\6\6\1\265\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\1\6\1\266\5\6\7\0\15\6"+
    "\20\0\1\57\1\6\1\0\2\6\1\267\4\6\7\0"+
    "\15\6\20\0\1\57\1\6\1\0\7\6\7\0\2\6"+
    "\1\270\12\6\20\0\1\57\1\6\1\0\6\6\1\271"+
    "\7\0\15\6\20\0\1\57\1\6\1\0\3\6\1\272"+
    "\3\6\7\0\15\6\20\0\1\57\1\6\1\0\7\6"+
    "\7\0\7\6\1\273\5\6\20\0\1\57\1\6\1\0"+
    "\5\6\1\274\1\6\7\0\15\6\20\0\1\57\1\6"+
    "\1\0\7\6\7\0\3\6\1\275\11\6\20\0\1\57"+
    "\1\6\1\0\1\6\1\276\5\6\7\0\15\6\20\0"+
    "\1\57\1\6\1\0\7\6\7\0\2\6\1\277\12\6"+
    "\20\0\1\57\1\6\1\0\6\6\1\300\7\0\15\6"+
    "\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6762];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\6\1\1\11\1\1\1\11"+
    "\1\1\2\11\15\1\1\11\1\1\2\11\1\1\6\11"+
    "\1\0\1\1\1\0\10\1\4\0\20\1\4\11\1\0"+
    "\12\1\2\0\25\1\2\0\25\1\1\0\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[192];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { return new Symbol(sym.CC, new token(yyline,"ESPECIALES", yytext()));
          }
        case 54: break;
        case 53: 
          { return new Symbol(sym.INCREMENTAR, new token(yyline,"RESERVADA", yytext()));
          }
        case 55: break;
        case 40: 
          { return new Symbol(sym.CADENA, new token(yyline,"RESERVADA", yytext()));
          }
        case 56: break;
        case 39: 
          { return new Symbol(sym.HACER, new token(yyline,"RESERVADA", yytext()));
          }
        case 57: break;
        case 33: 
          { return new Symbol(sym.NULO, new token(yyline,"RESERVADA", yytext()));
          }
        case 58: break;
        case 28: 
          { return new Symbol(sym.MMENOS, new token(yyline,"OPERADOR", yytext()));
          }
        case 59: break;
        case 19: 
          { return new Symbol(sym.PC, new token(yyline,"ESPECIALES", yytext()));
          }
        case 60: break;
        case 26: 
          { return new Symbol(sym.SI, new token(yyline,"RESERVADA", yytext()));
          }
        case 61: break;
        case 48: 
          { return new Symbol(sym.ENTONCES, new token(yyline,"RESERVADA", yytext()));
          }
        case 62: break;
        case 50: 
          { return new Symbol(sym.MIENTRAS, new token(yyline,"RESERVADA", yytext()));
          }
        case 63: break;
        case 34: 
          { return new Symbol(sym.LEER, new token(yyline,"RESERVADA", yytext()));
          }
        case 64: break;
        case 8: 
          { return new Symbol(sym.DIAGONAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 65: break;
        case 38: 
          { return new Symbol(sym.FALSO, new token(yyline,"RESERVADA", yytext()));
          }
        case 66: break;
        case 5: 
          { return new Symbol(sym.VARIABLE, new token(yyline,"ID",yytext()));
          }
        case 67: break;
        case 36: 
          { return new Symbol(sym.DESDE, new token(yyline,"RESERVADA", yytext()));
          }
        case 68: break;
        case 21: 
          { return new Symbol(sym.CA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 69: break;
        case 4: 
          { return new Symbol(sym.NUMERO, new token(yyline,"NUMERO", yytext(),false));
          }
        case 70: break;
        case 43: 
          { return new Symbol(sym.BOLEANO, new token(yyline,"RESERVADA", yytext()));
          }
        case 71: break;
        case 45: 
          { return new Symbol(sym.DEVOLVER, new token(yyline,"RESERVADA", yytext()));
          }
        case 72: break;
        case 42: 
          { return new Symbol(sym.DECIMAL, new token(yyline,"RESERVADA", yytext()));
          }
        case 73: break;
        case 3: 
          { /*ignore*/
          }
        case 74: break;
        case 35: 
          { return new Symbol(sym.SINO, new token(yyline,"RESERVADA", yytext()));
          }
        case 75: break;
        case 18: 
          { return new Symbol(sym.PA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 76: break;
        case 6: 
          { return new Symbol(sym.PUNTO, new token(yyline,"ESPECIALES", yytext()));
          }
        case 77: break;
        case 13: 
          { return new Symbol(sym.MODULO, new token(yyline,"OPERADOR", yytext()));
          }
        case 78: break;
        case 51: 
          { return new Symbol(sym.VERDADERO, new token(yyline,"RESERVADA", yytext()));
          }
        case 79: break;
        case 41: 
          { return new Symbol(sym.ENTERO, new token(yyline,"RESERVADA", yytext()));
          }
        case 80: break;
        case 14: 
          { return new Symbol(sym.IGUAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 81: break;
        case 9: 
          { return new Symbol(sym.MULTIPLICACION, new token(yyline,"OPERADOR", yytext()));
          }
        case 82: break;
        case 15: 
          { return new Symbol(sym.MAYORQUE, new token(yyline,"OPERADOR", yytext()));
          }
        case 83: break;
        case 30: 
          { return new Symbol(sym.DIFERENCIA, new token(yyline,"OPERADOR", yytext()));
          }
        case 84: break;
        case 25: 
          { return new Symbol(sym.CADENAS, new token(yyline,"CADENAS", yytext()));
          }
        case 85: break;
        case 16: 
          { return new Symbol(sym.MENORQUE, new token(yyline,"OPERADOR", yytext()));
          }
        case 86: break;
        case 31: 
          { return new Symbol(sym.FLOT, new token(yyline,"NUMERO", yytext(),true));
          }
        case 87: break;
        case 12: 
          { return new Symbol(sym.RESTA, new token(yyline,"OPERADOR", yytext()));
          }
        case 88: break;
        case 23: 
          { return new Symbol(sym.NOMCLASE, new token(yyline,"ID", yytext()));
          }
        case 89: break;
        case 11: 
          { return new Symbol(sym.SUMA, new token(yyline,"OPERADOR", yytext()));
          }
        case 90: break;
        case 49: 
          { return new Symbol(sym.ESCRIBIR, new token(yyline,"RESERVADA", yytext()));
          }
        case 91: break;
        case 32: 
          { return new Symbol(sym.AND, new token(yyline,"RESERVADA", yytext()));
          }
        case 92: break;
        case 1: 
          { yyclose(); 
    System.err.println("Caracter Invalido" + yytext() + "["+ yyline + "]");
    return new Symbol(sym.ERROR);
          }
        case 93: break;
        case 46: 
          { return new Symbol(sym.RETORNAR, new token(yyline,"RESERVADA", yytext()));
          }
        case 94: break;
        case 2: 
          { return new Symbol(sym.TAB, new token(yyline,"TAB",true, yytext()));
          }
        case 95: break;
        case 17: 
          { return new Symbol(sym.PCOMA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 96: break;
        case 52: 
          { return new Symbol(sym.PROPIEDADES, new token(yyline,"RESERVADA", yytext()));
          }
        case 97: break;
        case 47: 
          { return new Symbol(sym.EXTIENDE, new token(yyline,"RESERVADA", yytext()));
          }
        case 98: break;
        case 24: 
          { return new Symbol(sym.OR, new token(yyline,"RESERVADA", yytext()));
          }
        case 99: break;
        case 37: 
          { return new Symbol(sym.CLASE, new token(yyline,"RESERVADA", yytext()));
          }
        case 100: break;
        case 27: 
          { return new Symbol(sym.MMAS, new token(yyline,"OPERADOR", yytext()));
          }
        case 101: break;
        case 10: 
          { return new Symbol(sym.OPCION, new token(yyline,"OPERADOR", yytext()));
          }
        case 102: break;
        case 20: 
          { return new Symbol(sym.COMA, new token(yyline,"ESPECIALES", yytext()));
          }
        case 103: break;
        case 44: 
          { return new Symbol(sym.METODOS, new token(yyline,"RESERVADA", yytext()));
          }
        case 104: break;
        case 29: 
          { return new Symbol(sym.IIGUAL, new token(yyline,"OPERADOR", yytext()));
          }
        case 105: break;
        case 7: 
          { 
          }
        case 106: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   System.out.println("Fin de archivo encontrado");
  return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
