
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package tools;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 37;
  public static final int NUMERO = 10;
  public static final int DIFERENCIA = 40;
  public static final int DEVOLVER = 13;
  public static final int ENTERO = 53;
  public static final int SI = 24;
  public static final int RESTA = 32;
  public static final int PC = 45;
  public static final int DESDE = 12;
  public static final int ENTONCES = 14;
  public static final int PA = 44;
  public static final int FLOT = 54;
  public static final int INCREMENTAR = 19;
  public static final int CADENAS = 49;
  public static final int AND = 11;
  public static final int MAYORQUE = 38;
  public static final int IGUAL = 36;
  public static final int MMENOS = 30;
  public static final int OPCION = 41;
  public static final int SINO = 23;
  public static final int OR = 26;
  public static final int MIENTRAS = 21;
  public static final int EXTIENDE = 16;
  public static final int TAB = 6;
  public static final int FNLINEA = 51;
  public static final int ESCRIBIR = 15;
  public static final int SUMA = 31;
  public static final int CC = 48;
  public static final int CA = 47;
  public static final int EOF = 0;
  public static final int DECIMAL = 9;
  public static final int PROPIEDADES = 4;
  public static final int CLASE = 2;
  public static final int error = 1;
  public static final int COMA = 46;
  public static final int NULO = 22;
  public static final int CADENA = 8;
  public static final int MODULO = 34;
  public static final int NOMCLASE = 3;
  public static final int MMAS = 29;
  public static final int ERROR = 50;
  public static final int PCOMA = 42;
  public static final int BOLEANO = 7;
  public static final int MENORQUE = 39;
  public static final int METODOS = 5;
  public static final int PUNTO = 43;
  public static final int VARIABLE = 28;
  public static final int FALSO = 17;
  public static final int LEER = 20;
  public static final int HACER = 18;
  public static final int RETORNAR = 25;
  public static final int VERDADERO = 27;
  public static final int INDENT = 52;
  public static final int MULTIPLICACION = 33;
  public static final int IIGUAL = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASE",
  "NOMCLASE",
  "PROPIEDADES",
  "METODOS",
  "TAB",
  "BOLEANO",
  "CADENA",
  "DECIMAL",
  "NUMERO",
  "AND",
  "DESDE",
  "DEVOLVER",
  "ENTONCES",
  "ESCRIBIR",
  "EXTIENDE",
  "FALSO",
  "HACER",
  "INCREMENTAR",
  "LEER",
  "MIENTRAS",
  "NULO",
  "SINO",
  "SI",
  "RETORNAR",
  "OR",
  "VERDADERO",
  "VARIABLE",
  "MMAS",
  "MMENOS",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "MODULO",
  "IIGUAL",
  "IGUAL",
  "DIAGONAL",
  "MAYORQUE",
  "MENORQUE",
  "DIFERENCIA",
  "OPCION",
  "PCOMA",
  "PUNTO",
  "PA",
  "PC",
  "COMA",
  "CA",
  "CC",
  "CADENAS",
  "ERROR",
  "FNLINEA",
  "INDENT",
  "ENTERO",
  "FLOT"
  };
}

